In [1]:
import polars as pl
simple = pl.read_csv("data/simple_rules_abbreviations.csv")
simple = simple.sort(by="abbr_parts", descending=True)
volume_specific = [simple.filter(pl.col("volumes").str.contains(rf"{volume}|\*")) for volume in range(10)]

In [2]:
simple

shape: (344, 7)
┌──────────────┬──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬────────────┐
│ abbreviation ┆ expansion    ┆ translation ┆ stem        ┆ declension  ┆ volumes     ┆ abbr_parts │
│ ---          ┆ ---          ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---        │
│ str          ┆ str          ┆ str         ┆ str         ┆ str         ┆ str         ┆ i64        │
╞══════════════╪══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪════════════╡
│ benef. c. c. ┆ beneficium   ┆ Pfründe mit ┆ null        ┆ null        ┆ 7|8         ┆ 6          │
│ vel s. c.    ┆ cum cura vel ┆ oder ohne   ┆             ┆             ┆             ┆            │
│              ┆ sine c…      ┆ Seelsorg…   ┆             ┆             ┆             ┆            │
│ s. e. s. o.  ┆ sed eius sup ┆ null        ┆ null        ┆ null        ┆ 5           ┆ 6          │
│ n. c.        ┆ erveniente   ┆             ┆             ┆             ┆             ┆            │
│              ┆ obitu n…     ┆             ┆             ┆             ┆             ┆            │
│ ben. c. v.   ┆ beneficium   ┆ Pfründe mit ┆ null        ┆ null        ┆ 1           ┆ 5          │
│ s. c.        ┆ cum vel sine ┆ oder ohne   ┆             ┆             ┆             ┆            │
│              ┆ cura         ┆ Seelsorg…   ┆             ┆             ┆             ┆            │
│ benef. c. v. ┆ beneficium   ┆ Pfründe mit ┆ null        ┆ null        ┆ 6           ┆ 5          │
│ s. c.        ┆ cum vel sine ┆ oder ohne   ┆             ┆             ┆             ┆            │
│              ┆ cura         ┆ Seelsorg…   ┆             ┆             ┆             ┆            │
│ c. c. vel s. ┆ cum cura vel ┆ mit oder    ┆ null        ┆ null        ┆ 7|8         ┆ 5          │
│ c.           ┆ sine cura    ┆ ohne        ┆             ┆             ┆             ┆            │
│              ┆              ┆ Seelsorge   ┆             ┆             ┆             ┆            │
│ …            ┆ …            ┆ …           ┆ …           ┆ …           ┆ …           ┆ …          │
│ vic.         ┆ vicarius     ┆ Vikar, Stel ┆ vicari -i   ┆ o           ┆ 2|3|4|5|6|7 ┆ 1          │
│              ┆              ┆ lvertreter  ┆             ┆             ┆ |8|9        ┆            │
│ vicar.       ┆ vicaria      ┆ Vikarie,    ┆ vicari      ┆ a           ┆ 2|3|4|5|6|7 ┆ 1          │
│              ┆              ┆ Meßpriester ┆ -(a)e       ┆             ┆ |8|9        ┆            │
│              ┆              ┆ stelle      ┆             ┆             ┆             ┆            │
│ virg.        ┆ virgo        ┆ Jungfrau    ┆ virgin -is  ┆ konsonantis ┆ 1|2|4|5|6|7 ┆ 1          │
│              ┆              ┆             ┆             ┆ ch          ┆ |8|9        ┆            │
│ visit.       ┆ visitare     ┆ besuchen;   ┆ visit,      ┆ a-Konj.     ┆ 1|2|4|5|6|7 ┆ 1          │
│              ┆              ┆ kontrollier ┆ visitav,    ┆             ┆ |8|9        ┆            │
│              ┆              ┆ en          ┆ visitat     ┆             ┆             ┆            │
│ vulg.        ┆ vulgariter   ┆ gewöhnlich, ┆ null        ┆ null        ┆ *           ┆ 1          │
│              ┆              ┆ sonst; in   ┆             ┆             ┆             ┆            │
│              ┆              ┆ der Volk…   ┆             ┆             ┆             ┆            │
└──────────────┴──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴────────────┘

In [3]:
volume_specific[2]

shape: (189, 7)
┌──────────────┬──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬────────────┐
│ abbreviation ┆ expansion    ┆ translation ┆ stem        ┆ declension  ┆ volumes     ┆ abbr_parts │
│ ---          ┆ ---          ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---        │
│ str          ┆ str          ┆ str         ┆ str         ┆ str         ┆ str         ┆ i64        │
╞══════════════╪══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪════════════╡
│ abb. et.     ┆ abbas et     ┆ Abt und     ┆ abbat -is;  ┆ konsonantis ┆ 2|3|4|5|6|8 ┆ 3          │
│ conv.        ┆ conventus    ┆ Konvent     ┆ convent -us ┆ ch/u        ┆ |9          ┆            │
│ aep. et      ┆ archiepiscop ┆ Erzbischof, ┆ null        ┆ null        ┆ 2|3|4|5|9   ┆ 3          │
│ capit.       ┆ us,          ┆ Propst,     ┆             ┆             ┆             ┆            │
│              ┆ prepositus,  ┆ Dekan und … ┆             ┆             ┆             ┆            │
│              ┆ de…          ┆             ┆             ┆             ┆             ┆            │
│ dec. et cap. ┆ decanus,     ┆ Dekan,      ┆ null        ┆ null        ┆ 1|2|4       ┆ 3          │
│              ┆ capitulum et ┆ Kapitel und ┆             ┆             ┆             ┆            │
│              ┆ singuli …    ┆ die         ┆             ┆             ┆             ┆            │
│              ┆              ┆ einzeln…    ┆             ┆             ┆             ┆            │
│ dec. et      ┆ decanus,     ┆ Dekan,      ┆ null        ┆ null        ┆ 2|3|4|5|6|7 ┆ 3          │
│ capit.       ┆ capitulum et ┆ Kapitel und ┆             ┆             ┆ |8|9        ┆            │
│              ┆ singuli …    ┆ die         ┆             ┆             ┆             ┆            │
│              ┆              ┆ einzeln…    ┆             ┆             ┆             ┆            │
│ ep. et       ┆ episcopus et ┆ Bischof und ┆ null        ┆ null        ┆ 2|3|4|5|7|8 ┆ 3          │
│ capit.       ┆ capitulum    ┆ Kapitel     ┆             ┆             ┆ |9          ┆            │
│ …            ┆ …            ┆ …           ┆ …           ┆ …           ┆ …           ┆ …          │
│ vic.         ┆ vicarius     ┆ Vikar, Stel ┆ vicari -i   ┆ o           ┆ 2|3|4|5|6|7 ┆ 1          │
│              ┆              ┆ lvertreter  ┆             ┆             ┆ |8|9        ┆            │
│ vicar.       ┆ vicaria      ┆ Vikarie,    ┆ vicari      ┆ a           ┆ 2|3|4|5|6|7 ┆ 1          │
│              ┆              ┆ Meßpriester ┆ -(a)e       ┆             ┆ |8|9        ┆            │
│              ┆              ┆ stelle      ┆             ┆             ┆             ┆            │
│ virg.        ┆ virgo        ┆ Jungfrau    ┆ virgin -is  ┆ konsonantis ┆ 1|2|4|5|6|7 ┆ 1          │
│              ┆              ┆             ┆             ┆ ch          ┆ |8|9        ┆            │
│ visit.       ┆ visitare     ┆ besuchen;   ┆ visit,      ┆ a-Konj.     ┆ 1|2|4|5|6|7 ┆ 1          │
│              ┆              ┆ kontrollier ┆ visitav,    ┆             ┆ |8|9        ┆            │
│              ┆              ┆ en          ┆ visitat     ┆             ┆             ┆            │
│ vulg.        ┆ vulgariter   ┆ gewöhnlich, ┆ null        ┆ null        ┆ *           ┆ 1          │
│              ┆              ┆ sonst; in   ┆             ┆             ┆             ┆            │
│              ┆              ┆ der Volk…   ┆             ┆             ┆             ┆            │
└──────────────┴──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴────────────┘

In [4]:
rg = pl.read_csv("data/rg.csv")
rg = rg.sort(by="id_RG_all")

In [5]:
rg

shape: (235_832, 5)
┌────────┬───────┬─────────────────────────────────┬─────────────────────────────────┬────────────┐
│ volume ┆ nr_RG ┆ header_no_tags                  ┆ regest_no_tags                  ┆ id_RG_all  │
│ ---    ┆ ---   ┆ ---                             ┆ ---                             ┆ ---        │
│ i64    ┆ i64   ┆ str                             ┆ str                             ┆ str        │
╞════════╪═══════╪═════════════════════════════════╪═════════════════════════════════╪════════════╡
│ 1      ┆ 1     ┆ Abardus Alamannuso. s. Ant.     ┆ null                            ┆ 10100001-0 │
│ 1      ┆ 1     ┆ null                            ┆ qui portavit litteras d. pape … ┆ 10100001-1 │
│ 1      ┆ 2     ┆ Achatius Erhardi Asini de Mont… ┆ null                            ┆ 10100002-0 │
│ 1      ┆ 2     ┆ null                            ┆ de benef. ad coll. abb. etc. m… ┆ 10100002-1 │
│ 1      ┆ 3     ┆ Achatius Nicolai Wenke de Nisa… ┆ null                            ┆ 10100003-0 │
│ …      ┆ …     ┆ …                               ┆ …                               ┆ …          │
│ 10     ┆ 10625 ┆ null                            ┆ referentes quod olim Henricus … ┆ 11010625-3 │
│ 10     ┆ 10625 ┆ null                            ┆ referentes quod nonnulli aep.,… ┆ 11010625-4 │
│ 10     ┆ 10625 ┆ null                            ┆ de conserv. 7. mai. 82 S 810 2… ┆ 11010625-5 │
│ 10     ┆ 10625 ┆ null                            ┆ mon. et conv. in Zwifelto o. s… ┆ 11010625-6 │
│ 10     ┆ 10625 ┆ null                            ┆ solv. 591/4 fl. adc. pro annat… ┆ 11010625-7 │
└────────┴───────┴─────────────────────────────────┴─────────────────────────────────┴────────────┘

In [6]:
def expand_rg_simple(rg_texts, volume_specific_expansions):
    volumes = {}
    for volume in range(10):
        expansions = volume_specific_expansions[volume]
        texts = rg_texts.filter(pl.col("volume") == volume)
        
        for row in expansions.iter_rows(named=True):
            # since all abbreviations, but no expansions contain `.`, we don't need to worry about expanding what has already been expanded
            texts = texts.with_columns(pl.col("header_no_tags").str.replace_all(row["abbreviation"], row["expansion"], literal=True).alias("header_no_tags"))
            texts = texts.with_columns(pl.col("regest_no_tags").str.replace_all(row["abbreviation"], row["expansion"], literal=True).alias("regest_no_tags"))

        volumes[volume] = texts
    
    return pl.concat(volumes.values())

In [7]:
expanded_texts = expand_rg_simple(rg, volume_specific)

In [8]:
id = "10906306-3"
print(rg.filter(pl.col("id_RG_all") == id).get_column("regest_no_tags").item())
print(expanded_texts.filter(pl.col("id_RG_all") == id).get_column("regest_no_tags").item())

Dom. o. fr. min. e.m. op. Z. Traiect. dioc. de observ. nunc. ap. auct. ad instantiam genitoris Adolphi Gelrie et Juliacen. [ducis] et comitis Zutphanien. erecta sed adhuc non confecta: supplic. d. Adolpho duce de lic. dom. in d. op. de novo erigendi et fratres ad illam transferendi 16. mai. 1470 S 658 282rs.
Dom. o. frater minor e.m. oper Z. Traiect. diocesis de observitium nuncupatus apostolicus auct. ad instantiam genitoris Adolphi Gelrie et Juliacenon [ducis] et comitis Zutphanienon erecta sed adhuc non confecta: supplicentia d. Adolpho duce de licentia dom. in d. oper de novo erigendi et fratres ad illam transferendi 16. mai. 1470 S 658 282rs.

approximating the number of abbreviations by the number of `.`

In [9]:
# filtering for all volumes except 10, because we don't have any rules for volumes 10 yet and are dropping this one when expanding
counts_rg = rg.filter(pl.col("volume") != 10).with_columns(pl.col("header_no_tags").str.count_matches(r"\.").sum().alias("countH"), pl.col("regest_no_tags").str.count_matches(r"\.").sum().alias("countR"))
abbreviations_rg = counts_rg.row(0)[5] + counts_rg.row(0)[6]

counts_expanded = expanded_texts.with_columns(pl.col("header_no_tags").str.count_matches(r"\.").sum().alias("countH"), pl.col("regest_no_tags").str.count_matches(r"\.").sum().alias("countR"))
abbreviations_expanded = counts_expanded.row(0)[5] + counts_expanded.row(0)[6]

print(f"abbreviations in rg: {abbreviations_rg}")
print(f"abbreviations after expanding: {abbreviations_expanded}")

abbreviations in rg: 2483194
abbreviations after expanding: 1067861